### ISSUE TITLE
Test on Windows

### ISSUE THREAD

**Issue by tiagob** [tiagob/create-full-stack#130]

**Comment by tiagob** [comment]
Must run in PowerShell as Administrator for symlinks to work (required for expo-yarn-workspaces)
https://github.com/expo/expo/issues/6983#issuecomment-670927430

Still getting
```
error D:\Users\tiagob\dev\my-full-stack2\node_modules\mobile: Command failed.
Exit code: 1
Command: expo-yarn-workspaces postinstall && prettier --write ./__generated__
Arguments:
Directory: D:\Users\tiagob\dev\my-full-stack2\node_modules\mobile
Output:
internal/validators.js:120
    throw new ERR_INVALID_ARG_TYPE(name, 'string', value);
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received null
    at validateString (internal/validators.js:120:11)
    at Object.join (path.js:375:7)
    at symlinkNecessaryPackage (D:\Users\tiagob\dev\my-full-stack2\node_modules\expo-yarn-workspaces\bin\symlink-necessa
ry-packages.js:39:35)
    at symlinkNecessaryPackages (D:\Users\tiagob\dev\my-full-stack2\node_modules\expo-yarn-workspaces\bin\symlink-necess
ary-packages.js:17:3)
    at Object.<anonymous> (D:\Users\tiagob\dev\my-full-stack2\node_modules\expo-yarn-workspaces\bin\symlink-necessary-pa
ckages.js:81:3)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
```

**Comment by tiagob** [comment]
Without mobile included create-full-stack fails on lint

```
yarn run v1.22.5
$ eslint packages/** --ext ts,tsx --fix

D:\Users\tiagob\dev\apollo-server-express-web\packages\common\package.json
  0:0  error  Parsing error: "parserOptions.project" has been set for @typescript-eslint/parser.
The file does not match your project config: packages\common\package.json.
The extension for the file (.json) is non-standard. You should add "parserOptions.extraFileExtensions" to your config

D:\Users\tiagob\dev\apollo-server-express-web\packages\common\src\graphql\todos.graphql
  0:0  error  Parsing error: "parserOptions.project" has been set for @typescript-eslint/parser.
The file does not match your project config: packages\common\src\graphql\todos.graphql.
The extension for the file (.graphql) is non-standard. You should add "parserOptions.extraFileExtensions" to your config

D:\Users\tiagob\dev\apollo-server-express-web\packages\common\tsconfig.json
  0:0  error  Parsing error: "parserOptions.project" has been set for @typescript-eslint/parser.
The file does not match your project config: packages\common\tsconfig.json.
The extension for the file (.json) is non-standard. You should add "parserOptions.extraFileExtensions" to your config

D:\Users\tiagob\dev\apollo-server-express-web\packages\server\Dockerfile
  0:0  error  Parsing error: "parserOptions.project" has been set for @typescript-eslint/parser.
The file does not match your project config: packages\server\Dockerfile.
The extension for the file () is non-standard. You should add "parserOptions.extraFileExtensions" to your config

D:\Users\tiagob\dev\apollo-server-express-web\packages\server\package.json
  0:0  error  Parsing error: "parserOptions.project" has been set for @typescript-eslint/parser.
The file does not match your project config: packages\server\package.json.
The extension for the file (.json) is non-standard. You should add "parserOptions.extraFileExtensions" to your config

D:\Users\tiagob\dev\apollo-server-express-web\packages\server\README.md
  0:0  error  Parsing error: "parserOptions.project" has been set for @typescript-eslint/parser.
The file does not match your project config: packages\server\README.md.
The extension for the file (.md) is non-standard. You should add "parserOptions.extraFileExtensions" to your config

D:\Users\tiagob\dev\apollo-server-express-web\packages\server\tsconfig.build.json
  0:0  error  Parsing error: "parserOptions.project" has been set for @typescript-eslint/parser.
The file does not match your project config: packages\server\tsconfig.build.json.
The extension for the file (.json) is non-standard. You should add "parserOptions.extraFileExtensions" to your config

D:\Users\tiagob\dev\apollo-server-express-web\packages\server\tsconfig.json
  0:0  error  Parsing error: "parserOptions.project" has been set for @typescript-eslint/parser.
The file does not match your project config: packages\server\tsconfig.json.
The extension for the file (.json) is non-standard. You should add "parserOptions.extraFileExtensions" to your config

D:\Users\tiagob\dev\apollo-server-express-web\packages\web\package.json
  0:0  error  Parsing error: "parserOptions.project" has been set for @typescript-eslint/parser.
The file does not match your project config: packages\web\package.json.
The extension for the file (.json) is non-standard. You should add "parserOptions.extraFileExtensions" to your config

D:\Users\tiagob\dev\apollo-server-express-web\packages\web\public\favicon.ico
  0:0  error  Parsing error: "parserOptions.project" has been set for @typescript-eslint/parser.
The file does not match your project config: packages\web\public\favicon.ico.
The extension for the file (.ico) is non-standard. You should add "parserOptions.extraFileExtensions" to your config

D:\Users\tiagob\dev\apollo-server-express-web\packages\web\public\index.html
  0:0  error  Parsing error: "parserOptions.project" has been set for @typescript-eslint/parser.
The file does not match your project config: packages\web\public\index.html.
The extension for the file (.html) is non-standard. You should add "parserOptions.extraFileExtensions" to your config

D:\Users\tiagob\dev\apollo-server-express-web\packages\web\public\logo192.png
  0:0  error  Parsing error: "parserOptions.project" has been set for @typescript-eslint/parser.
The file does not match your project config: packages\web\public\logo192.png.
The extension for the file (.png) is non-standard. You should add "parserOptions.extraFileExtensions" to your config

D:\Users\tiagob\dev\apollo-server-express-web\packages\web\public\logo512.png
  0:0  error  Parsing error: "parserOptions.project" has been set for @typescript-eslint/parser.
The file does not match your project config: packages\web\public\logo512.png.
The extension for the file (.png) is non-standard. You should add "parserOptions.extraFileExtensions" to your config

D:\Users\tiagob\dev\apollo-server-express-web\packages\web\public\manifest.json
  0:0  error  Parsing error: "parserOptions.project" has been set for @typescript-eslint/parser.
The file does not match your project config: packages\web\public\manifest.json.
The extension for the file (.json) is non-standard. You should add "parserOptions.extraFileExtensions" to your config

D:\Users\tiagob\dev\apollo-server-express-web\packages\web\public\robots.txt
  0:0  error  Parsing error: "parserOptions.project" has been set for @typescript-eslint/parser.
The file does not match your project config: packages\web\public\robots.txt.
The extension for the file (.txt) is non-standard. You should add "parserOptions.extraFileExtensions" to your config

D:\Users\tiagob\dev\apollo-server-express-web\packages\web\README.md
  0:0  error  Parsing error: "parserOptions.project" has been set for @typescript-eslint/parser.
The file does not match your project config: packages\web\README.md.
The extension for the file (.md) is non-standard. You should add "parserOptions.extraFileExtensions" to your config

D:\Users\tiagob\dev\apollo-server-express-web\packages\web\src\index.css
  0:0  error  Parsing error: "parserOptions.project" has been set for @typescript-eslint/parser.
The file does not match your project config: packages\web\src\index.css.
The extension for the file (.css) is non-standard. You should add "parserOptions.extraFileExtensions" to your config

D:\Users\tiagob\dev\apollo-server-express-web\packages\web\tsconfig.json
  0:0  error  Parsing error: "parserOptions.project" has been set for @typescript-eslint/parser.
The file does not match your project config: packages\web\tsconfig.json.
The extension for the file (.json) is non-standard. You should add "parserOptions.extraFileExtensions" to your config

✖ 18 problems (18 errors, 0 warnings)

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
`yarnpkg --cwd apollo-server-express-web lint` failed
error Command failed.
Exit code: 1
Command: D:\Users\tiagob\AppData\Local\Yarn\bin\create-full-stack
Arguments: apollo-server-express-web
Directory: D:\Users\tiagob\dev
Output:

info Visit https://yarnpkg.com/en/docs/cli/create for documentation about this command.
```
